### ISSUE TITLE
pipがpython3ベースになっている環境で警告を出したい

### ISSUE THREAD

**Issue by hiroshi-cl** [icpc-jag/rime-plus#6]
幾つかの新しい環境ではpipコマンドでインストールするとpython3が使われてしまう。そういったとき普通に実行時エラーになってしまうがより親切な警告(python2を使え)を出したい。

**Comment by orisano** [comment]
setuptoolsにそういう項目があるのかわかりませんが
あるならそれを使うべきだと思いますし、ないのなら[six](https://pypi.python.org/pypi/six)を使ってsetup.pyを
```python
if six.PY3
    six.print_("rime-plus support only python2. please `python2 -m pip install rime-plus`")
else:
    setup()
```
の様にするといいと思います

**Comment by hiroshi-cl** [comment]
なるほど。プルリクください

**Comment by orisano** [comment]
プルリク出しました。
なんか英語が怪しいので確認お願いします。

**Comment by hiroshi-cl** [comment]
どうせ他のところも怪しいので細かいところは気にしないということで…

**Comment by hiroshi-cl** [comment]
#20 で解決
